export const SET_CAROUSEL = "SET_CAROUSEL";
export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const SET_FILM_DANG_CHIEU = "SET_FILM_DANG_CHIEU";
export const SET_FILM_SAP_CHIEU = "SET_FILM_SAP_CHIEU";
export const SET_HE_THONG_RAP_CHIEU = "SET_HE_THONG_RAP_CHIEU";
